# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from dreamcatcher.api.endpoints_api import EndpointsApi  # noqa: E501


class TestEndpointsApi(unittest.TestCase):
    """EndpointsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EndpointsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_dreamcatcher_web_endpoint_controller_index(self) -> None:
        """Test case for dreamcatcher_web_endpoint_controller_index

        List endpoints  # noqa: E501
        """
        pass

    def test_dreamcatcher_web_endpoint_controller_invoke_chat_completions(self) -> None:
        """Test case for dreamcatcher_web_endpoint_controller_invoke_chat_completions

        Invoke a chat completion  # noqa: E501
        """
        pass

    def test_dreamcatcher_web_endpoint_controller_invoke_chat_completions__2(self) -> None:
        """Test case for dreamcatcher_web_endpoint_controller_invoke_chat_completions__2

        Invoke a chat completion  # noqa: E501
        """
        pass

    def test_dreamcatcher_web_endpoint_controller_invoke_completions(self) -> None:
        """Test case for dreamcatcher_web_endpoint_controller_invoke_completions

        Invoke a completion  # noqa: E501
        """
        pass

    def test_dreamcatcher_web_endpoint_controller_models(self) -> None:
        """Test case for dreamcatcher_web_endpoint_controller_models

        Lists upstreams (ie models) for an endpoint  # noqa: E501
        """
        pass

    def test_dreamcatcher_web_endpoint_controller_show(self) -> None:
        """Test case for dreamcatcher_web_endpoint_controller_show

        Get an endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
