# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.dlp_policies_api import DlpPoliciesApi


class TestDlpPoliciesApi(unittest.TestCase):
    """DlpPoliciesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DlpPoliciesApi()

    def tearDown(self) -> None:
        pass

    def test_dreamcatcher_web_presidio_policy_controller_show(self) -> None:
        """Test case for dreamcatcher_web_presidio_policy_controller_show

        Get a DLP policy
        """
        pass


if __name__ == '__main__':
    unittest.main()
