# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.dlp_zsner_policy import DlpZsnerPolicy

class TestDlpZsnerPolicy(unittest.TestCase):
    """DlpZsnerPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DlpZsnerPolicy:
        """Test DlpZsnerPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DlpZsnerPolicy`
        """
        model = DlpZsnerPolicy()
        if include_optional:
            return DlpZsnerPolicy(
                active = True,
                anonymizer = openapi_client.models.dlp_zsner_policy_anonymizer.DlpZsnerPolicy_anonymizer(
                    type = 'replace', ),
                entities = [
                    ''
                    ],
                name = '',
                response = 'block',
                score_threshold = 1.337
            )
        else:
            return DlpZsnerPolicy(
        )
        """

    def testDlpZsnerPolicy(self):
        """Test DlpZsnerPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
