# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.openai_api import OpenaiApi


class TestOpenaiApi(unittest.TestCase):
    """OpenaiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenaiApi()

    def tearDown(self) -> None:
        pass

    def test_stubidity_open_ai_chat_completion_call(self) -> None:
        """Test case for stubidity_open_ai_chat_completion_call

        Chat completion
        """
        pass

    def test_stubidity_open_ai_completion_call(self) -> None:
        """Test case for stubidity_open_ai_completion_call

        Completion
        """
        pass

    def test_stubidity_open_ai_embedding_call(self) -> None:
        """Test case for stubidity_open_ai_embedding_call

        Embedding
        """
        pass

    def test_stubidity_open_ai_embedding_call__2(self) -> None:
        """Test case for stubidity_open_ai_embedding_call__2

        Embedding
        """
        pass


if __name__ == '__main__':
    unittest.main()
