# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.embedding_response_inner import EmbeddingResponseInner

class TestEmbeddingResponseInner(unittest.TestCase):
    """EmbeddingResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EmbeddingResponseInner:
        """Test EmbeddingResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EmbeddingResponseInner`
        """
        model = EmbeddingResponseInner()
        if include_optional:
            return EmbeddingResponseInner(
                embedding = [
                    1.337
                    ]
            )
        else:
            return EmbeddingResponseInner(
        )
        """

    def testEmbeddingResponseInner(self):
        """Test EmbeddingResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
