# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dreamcatcher.models.dlp_policy_params import DlpPolicyParams  # noqa: E501

class TestDlpPolicyParams(unittest.TestCase):
    """DlpPolicyParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DlpPolicyParams:
        """Test DlpPolicyParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DlpPolicyParams`
        """
        model = DlpPolicyParams()  # noqa: E501
        if include_optional:
            return DlpPolicyParams(
                dlp_policy = dreamcatcher.models.dlp_policy.DlpPolicy(
                    active = True, 
                    anonymizer = dreamcatcher.models.dlp_policy_anonymizer.DlpPolicy_anonymizer(
                        type = 'replace', ), 
                    entities = [
                        'MEDICAL_LICENSE'
                        ], 
                    name = '', 
                    response = 'block', 
                    score_threshold = 1.337, )
            )
        else:
            return DlpPolicyParams(
        )
        """

    def testDlpPolicyParams(self):
        """Test DlpPolicyParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
