# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dreamcatcher.models.list_endpoint_response_inner import ListEndpointResponseInner  # noqa: E501

class TestListEndpointResponseInner(unittest.TestCase):
    """ListEndpointResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListEndpointResponseInner:
        """Test ListEndpointResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListEndpointResponseInner`
        """
        model = ListEndpointResponseInner()  # noqa: E501
        if include_optional:
            return ListEndpointResponseInner(
                name = ''
            )
        else:
            return ListEndpointResponseInner(
        )
        """

    def testListEndpointResponseInner(self):
        """Test ListEndpointResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
