# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dreamcatcher.models.list_models_response import ListModelsResponse  # noqa: E501

class TestListModelsResponse(unittest.TestCase):
    """ListModelsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListModelsResponse:
        """Test ListModelsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListModelsResponse`
        """
        model = ListModelsResponse()  # noqa: E501
        if include_optional:
            return ListModelsResponse(
                data = [
                    dreamcatcher.models.list_models_response_data_inner.ListModelsResponse_data_inner(
                        created = 1.337, 
                        id = '', 
                        object = '', 
                        owned_by = '', )
                    ],
                object = ''
            )
        else:
            return ListModelsResponse(
        )
        """

    def testListModelsResponse(self):
        """Test ListModelsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
