# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dreamcatcher.models.content_moderation_policy import ContentModerationPolicy  # noqa: E501

class TestContentModerationPolicy(unittest.TestCase):
    """ContentModerationPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentModerationPolicy:
        """Test ContentModerationPolicy
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentModerationPolicy`
        """
        model = ContentModerationPolicy()  # noqa: E501
        if include_optional:
            return ContentModerationPolicy(
                active = True,
                blocked_content_types = [
                    'toxic'
                    ],
                name = '',
                score_threshold = 1.337
            )
        else:
            return ContentModerationPolicy(
        )
        """

    def testContentModerationPolicy(self):
        """Test ContentModerationPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
