# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dreamcatcher.models.chat_completion_response_choices_inner import ChatCompletionResponseChoicesInner  # noqa: E501

class TestChatCompletionResponseChoicesInner(unittest.TestCase):
    """ChatCompletionResponseChoicesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatCompletionResponseChoicesInner:
        """Test ChatCompletionResponseChoicesInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatCompletionResponseChoicesInner`
        """
        model = ChatCompletionResponseChoicesInner()  # noqa: E501
        if include_optional:
            return ChatCompletionResponseChoicesInner(
                message = dreamcatcher.models.chat_completion_message.Chat completion message(
                    content = '', 
                    role = '', )
            )
        else:
            return ChatCompletionResponseChoicesInner(
        )
        """

    def testChatCompletionResponseChoicesInner(self):
        """Test ChatCompletionResponseChoicesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
