# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dreamcatcher.models.list_models_response_data_inner import ListModelsResponseDataInner  # noqa: E501

class TestListModelsResponseDataInner(unittest.TestCase):
    """ListModelsResponseDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListModelsResponseDataInner:
        """Test ListModelsResponseDataInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListModelsResponseDataInner`
        """
        model = ListModelsResponseDataInner()  # noqa: E501
        if include_optional:
            return ListModelsResponseDataInner(
                created = 1.337,
                id = '',
                object = '',
                owned_by = ''
            )
        else:
            return ListModelsResponseDataInner(
        )
        """

    def testListModelsResponseDataInner(self):
        """Test ListModelsResponseDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
