# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dreamcatcher.models.embedding import Embedding  # noqa: E501

class TestEmbedding(unittest.TestCase):
    """Embedding unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Embedding:
        """Test Embedding
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Embedding`
        """
        model = Embedding()  # noqa: E501
        if include_optional:
            return Embedding(
                input = '',
                model = ''
            )
        else:
            return Embedding(
                input = '',
                model = '',
        )
        """

    def testEmbedding(self):
        """Test Embedding"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
