# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from dreamcatcher.models.dlp_zsner_policy_anonymizer import DlpZsnerPolicyAnonymizer  # noqa: E501

class TestDlpZsnerPolicyAnonymizer(unittest.TestCase):
    """DlpZsnerPolicyAnonymizer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DlpZsnerPolicyAnonymizer:
        """Test DlpZsnerPolicyAnonymizer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DlpZsnerPolicyAnonymizer`
        """
        model = DlpZsnerPolicyAnonymizer()  # noqa: E501
        if include_optional:
            return DlpZsnerPolicyAnonymizer(
                type = 'replace'
            )
        else:
            return DlpZsnerPolicyAnonymizer(
        )
        """

    def testDlpZsnerPolicyAnonymizer(self):
        """Test DlpZsnerPolicyAnonymizer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
