# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, StrictStr, conlist
from dreamcatcher.models.completion_response_choices_inner import CompletionResponseChoicesInner

class CompletionResponse(BaseModel):
    """
    A completion response from the model.  # noqa: E501
    """
    choices: Optional[conlist(CompletionResponseChoicesInner)] = None
    id: Optional[StrictStr] = None
    model: Optional[StrictStr] = None
    __properties = ["choices", "id", "model"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CompletionResponse:
        """Create an instance of CompletionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in choices (list)
        _items = []
        if self.choices:
            for _item in self.choices:
                if _item:
                    _items.append(_item.to_dict())
            _dict['choices'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CompletionResponse:
        """Create an instance of CompletionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CompletionResponse.parse_obj(obj)

        _obj = CompletionResponse.parse_obj({
            "choices": [CompletionResponseChoicesInner.from_dict(_item) for _item in obj.get("choices")] if obj.get("choices") is not None else None,
            "id": obj.get("id"),
            "model": obj.get("model")
        })
        return _obj


