# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist
from dreamcatcher.models.chat_completion_message import ChatCompletionMessage

class CreateChatCompletion(BaseModel):
    """
    Creates a model response for the given chat conversation.  # noqa: E501
    """
    messages: conlist(ChatCompletionMessage) = Field(...)
    model: StrictStr = Field(...)
    stream: Optional[StrictBool] = None
    __properties = ["messages", "model", "stream"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateChatCompletion:
        """Create an instance of CreateChatCompletion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in messages (list)
        _items = []
        if self.messages:
            for _item in self.messages:
                if _item:
                    _items.append(_item.to_dict())
            _dict['messages'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateChatCompletion:
        """Create an instance of CreateChatCompletion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateChatCompletion.parse_obj(obj)

        _obj = CreateChatCompletion.parse_obj({
            "messages": [ChatCompletionMessage.from_dict(_item) for _item in obj.get("messages")] if obj.get("messages") is not None else None,
            "model": obj.get("model"),
            "stream": obj.get("stream")
        })
        return _obj


