# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional, Union
from pydantic import BaseModel, StrictBool, StrictFloat, StrictInt, StrictStr, conlist, validator
from dreamcatcher.models.dlp_policy_anonymizer import DlpPolicyAnonymizer
from dreamcatcher.models.dlp_zsner_policy_entities_inner import DlpZsnerPolicyEntitiesInner

class DlpZsnerPolicy(BaseModel):
    """
    DlpZsnerPolicy
    """
    active: Optional[StrictBool] = None
    anonymizer: Optional[DlpPolicyAnonymizer] = None
    entities: Optional[conlist(DlpZsnerPolicyEntitiesInner)] = None
    id: Optional[Union[StrictFloat, StrictInt]] = None
    name: Optional[StrictStr] = None
    response: Optional[StrictStr] = None
    score_threshold: Optional[Union[StrictFloat, StrictInt]] = None
    __properties = ["active", "anonymizer", "entities", "id", "name", "response", "score_threshold"]

    @validator('response')
    def response_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('block', 'alert', 'anonymize'):
            raise ValueError("must be one of enum values ('block', 'alert', 'anonymize')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DlpZsnerPolicy:
        """Create an instance of DlpZsnerPolicy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of anonymizer
        if self.anonymizer:
            _dict['anonymizer'] = self.anonymizer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in entities (list)
        _items = []
        if self.entities:
            for _item in self.entities:
                if _item:
                    _items.append(_item.to_dict())
            _dict['entities'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DlpZsnerPolicy:
        """Create an instance of DlpZsnerPolicy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DlpZsnerPolicy.parse_obj(obj)

        _obj = DlpZsnerPolicy.parse_obj({
            "active": obj.get("active"),
            "anonymizer": DlpPolicyAnonymizer.from_dict(obj.get("anonymizer")) if obj.get("anonymizer") is not None else None,
            "entities": [DlpZsnerPolicyEntitiesInner.from_dict(_item) for _item in obj.get("entities")] if obj.get("entities") is not None else None,
            "id": obj.get("id"),
            "name": obj.get("name"),
            "response": obj.get("response"),
            "score_threshold": obj.get("score_threshold")
        })
        return _obj


