# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr, validator

class DlpZsnerPolicyAnonymizer(BaseModel):
    """
    DlpZsnerPolicyAnonymizer
    """
    type: Optional[StrictStr] = None
    __properties = ["type"]

    @validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('replace', 'encrypt'):
            raise ValueError("must be one of enum values ('replace', 'encrypt')")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DlpZsnerPolicyAnonymizer:
        """Create an instance of DlpZsnerPolicyAnonymizer from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DlpZsnerPolicyAnonymizer:
        """Create an instance of DlpZsnerPolicyAnonymizer from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DlpZsnerPolicyAnonymizer.parse_obj(obj)

        _obj = DlpZsnerPolicyAnonymizer.parse_obj({
            "type": obj.get("type")
        })
        return _obj


